name: "AWS S3 Sync with CloudFront Cache invalidation (Invalidation paths option)"
description: "Sync a directory to an AWS S3 bucket and invalidate the CloudFront cache"
author: exatasmente
runs:
  using: docker
  image: Dockerfile
branding:
  icon: refresh-cw
  color: green
